<?php

declare(strict_types=1);

namespace Capell\Core\Facades;

use Capell\Core\Support\CapellCoreManager;
use Illuminate\Support\Facades\Facade;

/**
 * @method static void flushOctaneState()
 * @method static ?string getInstalledPrettyVersion(string $packageName)
 * @method static \Capell\Core\Settings\CoreSettings settings()
 * @method static static registerAsset(\Capell\Core\Data\AssetData $asset)
 * @method static \Illuminate\Support\Collection<string, \Capell\Core\Data\AssetData> getAssets()
 * @method static \Capell\Core\Data\AssetData getAsset(\Capell\Core\Enums\AssetEnum|string $name)
 * @method static bool hasAsset(string $name)
 * @method static mixed rememberCache(\BackedEnum|string $key, \Closure $callback, \Closure|\DateTimeInterface|\DateInterval|int|null $ttl = null)
 * @method static mixed getFromCache(string $key)
 * @method static void setToCache(string $key, mixed $value, \Closure|\DateTimeInterface|\DateInterval|int|null $ttl = null)
 * @method static bool cacheExists(string $key)
 * @method static void removeCacheKey(string $key)
 * @method static void flushCache()
 * @method static void flushLocalCache()
 * @method static list<string> getCloneableRelations(string $model)
 * @method static void addCloneableRelations(string $model, string $relation)
 * @method static static registerComponent(\BackedEnum|string $type, \BackedEnum|string $name, string $component)
 * @method static static registerComponents(\BackedEnum|string $type, array<mixed> $components)
 * @method static array<mixed> getComponents(\BackedEnum|string|null $type = null)
 * @method static string getComponent(\BackedEnum|string $type, string $name)
 * @method static array<mixed> getCoreComponents(\BackedEnum|string|null $type = null)
 * @method static bool hasComponent(\BackedEnum|string $type, string $name)
 * @method static static registerDiscoverableComponents(string $in, ?string $for = null)
 * @method static static discoverComponents(string $in, ?string $for = null)
 * @method static array<mixed> getDiscoverableComponents()
 * @method static bool hasCachedComponents()
 * @method static void cacheComponents()
 * @method static void restoreCachedComponents()
 * @method static void clearCachedComponents()
 * @method static string getComponentCachePath()
 * @method static \Illuminate\Support\Collection<string, \Capell\Core\Data\DefaultPageData> loadDefaultPages()
 * @method static \Illuminate\Support\Collection<string, \Capell\Core\Data\DefaultPageData> getDefaultPages()
 * @method static \Capell\Core\Data\DefaultPageData getDefaultPage(string $key)
 * @method static self addDefaultPage(string $key, string $label, \Closure $callback)
 * @method static void serving(\Closure $callback)
 * @method static \Capell\Core\Support\Subscriber\SubscriberRegistry<object> subscriberManager()
 * @method static void registerModelInterceptor(string $model, string $interceptorClass, \BackedEnum|array<mixed>|string|null $key = null, int $priority = 0)
 * @method static void unregisterModelInterceptor(string $model, string $interceptorClass, \BackedEnum|array<mixed>|string|null $key = null)
 * @method static void replaceModelInterceptor(string $model, string $oldInterceptorClass, string $newInterceptorClass, \BackedEnum|array<mixed>|string|null $key = null, int $priority = 0)
 * @method static TModel createModel<TModel of \Illuminate\Database\Eloquent\Model>(class-string<TModel> $model, \BackedEnum|array<mixed>|string $key, callable $persist, string $interceptorInterface)
 * @method static TModel createOrUpdateModel<TModel of \Illuminate\Database\Eloquent\Model>(class-string<TModel> $model, \BackedEnum|array<mixed>|string $key, callable $persist, string $interceptorInterface)
 * @method static array<mixed> getInterceptorsForModelAndKey(string $model, \BackedEnum|array<mixed>|string|null $key)
 * @method static array<mixed> mergeModelInterceptorData(array<mixed> $defaults, array<mixed> $data)
 * @method static array<string, class-string<\Illuminate\Database\Eloquent\Model>> getModels()
 * @method static static registerModels(array<int|string, \BackedEnum|class-string<\Illuminate\Database\Eloquent\Model>> $models = [])
 * @method static static registerPackage(string $name, \Capell\Core\Enums\PackageTypeEnum $type = \Capell\Core\Enums\PackageTypeEnum::Plugin, ?string $serviceProviderClass = null, ?string $path = null, ?string $version = null, ?string $setting = null, array<mixed> $permissions = [], \Closure|string|null $description = null, ?string $setupCommand = null, array<mixed> $setupParams = [], ?string $installCommand = null, array<mixed> $installParams = [], bool $defaultSelected = false)
 * @method static static registerManifestPackage(\Capell\Core\Support\Manifest\CapellManifestData $manifest, ?string $version = null)
 * @method static \Illuminate\Support\Collection<string, \Capell\Core\Data\PackageData> getPackages(bool $withoutCore = true, bool $sortByDependencies = false)
 * @method static bool hasPackage(string $name)
 * @method static \Capell\Core\Data\PackageData getPackage(string $name)
 * @method static bool isPackageInstalled(string $name)
 * @method static bool isPackageEnabled(string $name)
 * @method static bool isPackageAvailable(string $name)
 * @method static \Illuminate\Support\Collection<string, \Capell\Core\Data\PackageData> getInstalledPackages()
 * @method static \Illuminate\Support\Collection<string, \Illuminate\Support\Collection<int, \Capell\Core\Data\PackageData>> getPackagesGroupedByProductGroup(?string $tier = null, bool $withoutCore = true)
 * @method static array<mixed> getPackageRequirements(string $name)
 * @method static array<mixed> getMissingRequirements(string $name)
 * @method static bool canInstallPackage(string $name)
 * @method static \Illuminate\Support\Collection<string, \Capell\Core\Data\PackageData> getDependentInstalledPackages(string $name)
 * @method static bool canUninstallPackage(string $name)
 * @method static void forcePackageInstalled(string $name, bool $installed = true)
 * @method static void markPackageInstalled(string $name)
 * @method static void markPackageInstalling(string $name)
 * @method static void markPackageFailed(string $name, string $message)
 * @method static void markPackageDisabled(string $name)
 * @method static void markPackageUninstalled(string $name)
 * @method static bool arePackageRequirementsInstalled(array<mixed> $requirements)
 * @method static void clearPackages()
 * @method static void clearExtensionCache()
 * @method static array<mixed> getInstalledExtensionNames()
 * @method static static registerPageType(\Capell\Core\Data\PageTypeData $type)
 * @method static \Illuminate\Support\Collection<string, \Capell\Core\Data\PageTypeData> getPageTypes()
 * @method static \Capell\Core\Data\PageTypeData getPageType(\Capell\Core\Enums\BlueprintSubjectEnum|string $name)
 * @method static bool hasPageType(\Capell\Core\Enums\BlueprintSubjectEnum|string $name)
 * @method static static registerPageVariation(\Capell\Core\Data\PageVariationData $pageData)
 * @method static ?\Capell\Core\Data\PageVariationData getPageVariation(string $name)
 * @method static bool hasPageVariation(?string $name)
 * @method static array<string, \Capell\Core\Data\PageVariationData> getPageVariations()
 * @method static list<string> getPageVariationNames()
 * @method static list<class-string<\Illuminate\Database\Eloquent\Model>> getPageVariationModels()
 * @method static void registerProtectedTable(\Closure|string $table)
 * @method static array<mixed> getProtectedTables()
 * @method static static registerVendorAsset(\Capell\Core\Data\VendorAssetData $asset)
 * @method static bool hasVendorAssets(\Capell\Core\Enums\VendorAssetEnum $type)
 * @method static \Illuminate\Support\Collection<int, \Capell\Core\Data\VendorAssetData> getVendorAssetsForType(\Capell\Core\Enums\VendorAssetEnum $type)
 * @method static \Illuminate\Support\Collection<string, array<int, \Capell\Core\Data\VendorAssetData>> getAllVendorAssets()
 *
 * @mixin CapellCoreManager
 */
class CapellCore extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return CapellCoreManager::class;
    }
}
