<?php

declare(strict_types=1);

$root = getenv('CAPELL_README_ENGINEERING_STANDARDS_ROOT') ?: dirname(__DIR__);
$metricsRelativePath = 'docs/reference/readme-engineering-metrics.json';
$arguments = array_map(
    static fn (mixed $argument): string => (string) $argument,
    is_array($_SERVER['argv'] ?? null) ? $_SERVER['argv'] : [],
);

if (in_array('--update', $arguments, true)) {
    $packageCatalogueTest = optionValue($arguments, '--package-catalogue-test')
        ?? getenv('CAPELL_FIRST_PARTY_CATALOGUE_TEST');

    if (! is_string($packageCatalogueTest) || trim($packageCatalogueTest) === '') {
        fail('--package-catalogue-test or CAPELL_FIRST_PARTY_CATALOGUE_TEST is required when updating metrics.');
    }

    $packageCount = packageCountFromCatalogueTest($packageCatalogueTest);
    $testListOutput = optionValue($arguments, '--test-list-output');
    $testCount = is_string($testListOutput) && trim($testListOutput) !== ''
        ? testCountFromListOutput($testListOutput)
        : testCountFromPest($root);
    $metricsPath = $root . '/' . $metricsRelativePath;
    $metrics = [
        'schema_version' => 1,
        'generated_by' => 'scripts/check-readme-engineering-standards.php',
        'package_count' => $packageCount,
        'package_count_source' => 'capell-app/tests/Feature/Marketplace/FirstPartyPackageCatalogueTest.php',
        'test_count' => $testCount,
        'test_count_source' => 'vendor/bin/pest --list-tests --configuration=phpunit.xml',
    ];

    writeJson($metricsPath, $metrics);
    fwrite(STDOUT, sprintf(
        'README metrics updated: package_count=%d, test_count=%d.%s',
        $packageCount,
        $testCount,
        PHP_EOL,
    ));

    exit(0);
}

$contracts = [
    'README declares a live test matrix badge' => ['README.md', 'test-full.yml?branch=main&style=flat-square&label=test%20matrix'],
    'README declares a live quality gates badge' => ['README.md', 'code-quality-and-styling.yml?branch=main&style=flat-square&label=quality%20gates'],
    'README declares live coverage' => ['README.md', 'img.shields.io/codecov/c/github/capell-app/capell'],
    'README declares a live first-party package count badge' => ['README.md', 'img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fraw.githubusercontent.com%2Fcapell-app%2Fcapell%2Fmain%2Fdocs%2Freference%2Freadme-engineering-metrics.json&query=%24.package_count&label=first-party%20packages'],
    'README declares a live Core Pest test count badge' => ['README.md', 'img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fraw.githubusercontent.com%2Fcapell-app%2Fcapell%2Fmain%2Fdocs%2Freference%2Freadme-engineering-metrics.json&query=%24.test_count&label=Core%20Pest%20tests'],
    'README explains the generated engineering metrics source' => ['README.md', 'check-readme-engineering-standards.php --update'],
    'README declares PHPStan level 8' => ['README.md', 'PHPStan-level%208'],
    'README declares 99.2% typed parameters' => ['README.md', 'parameters%20typed-99.2%25'],
    'README declares audited dependencies' => ['README.md', 'dependencies-audited'],
    'PHPStan is configured at level 8' => ['phpstan/common.neon', 'level: 8'],
    'PHPStan enforces 99.2% parameter types' => ['phpstan/common.neon', 'param_type: 99.2'],
    'quality workflow validates README standards' => ['.github/workflows/code-quality-and-styling.yml', 'composer run check:readme-engineering-standards'],
    'quality workflow runs on main pull requests' => ['.github/workflows/code-quality-and-styling.yml', "pull_request:\n    branches:\n      - main"],
    'quality workflow runs PHPStan' => ['.github/workflows/code-quality-and-styling.yml', 'composer phpstan'],
    'quality workflow audits locked dependencies' => ['.github/workflows/code-quality-and-styling.yml', 'composer audit --locked'],
    'full test matrix covers Laravel 13' => ['scripts/test-all/TestAllMatrix.php', "'laravel' => '13.*'"],
    'coverage workflow enforces 90% coverage' => ['.github/workflows/coverage-release.yml', 'Merge Clover shards and enforce 90% coverage'],
    'metrics source is generated by this checker' => ['docs/reference/readme-engineering-metrics.json', '"generated_by": "scripts/check-readme-engineering-standards.php"'],
    'metrics package count is anchored to the Marketplace catalogue test' => ['docs/reference/readme-engineering-metrics.json', '"package_count_source": "capell-app/tests/Feature/Marketplace/FirstPartyPackageCatalogueTest.php"'],
    'metrics test count is sourced from Pest test discovery' => ['docs/reference/readme-engineering-metrics.json', '"test_count_source": "vendor/bin/pest --list-tests --configuration=phpunit.xml"'],
];

/** @var array<string, string> $contents */
$contents = [];
$failures = [];

foreach ($contracts as $description => [$relativePath, $expected]) {
    if (! array_key_exists($relativePath, $contents)) {
        $path = $root . '/' . $relativePath;
        $fileContents = file_get_contents($path);

        if ($fileContents === false) {
            $failures[] = $relativePath . ' could not be read.';

            continue;
        }

        $contents[$relativePath] = $fileContents;
    }

    if (! str_contains($contents[$relativePath], $expected)) {
        $failures[] = sprintf('%s (%s).', $description, $relativePath);
    }
}

if ($failures !== []) {
    fwrite(STDERR, "README engineering standards are out of sync:\n");

    foreach ($failures as $failure) {
        fwrite(STDERR, sprintf('- %s%s', $failure, PHP_EOL));
    }

    exit(1);
}

try {
    $metrics = json_decode(
        (string) file_get_contents($root . '/' . $metricsRelativePath),
        true,
        flags: JSON_THROW_ON_ERROR,
    );
} catch (JsonException|TypeError) {
    $metrics = [];
}

$packageCount = is_array($metrics) && is_int($metrics['package_count'] ?? null)
    ? $metrics['package_count']
    : null;
$testCount = is_array($metrics) && is_int($metrics['test_count'] ?? null)
    ? $metrics['test_count']
    : null;

if ($packageCount === null || $packageCount < 1 || $testCount === null || $testCount < 1) {
    fwrite(STDERR, "README engineering metrics are missing valid package/test counts.\n");

    exit(1);
}

fwrite(STDOUT, sprintf(
    'README engineering standards are verified. Metrics: %d first-party packages; %s Core Pest tests.%s',
    $packageCount,
    number_format($testCount),
    PHP_EOL,
));

/** @param array<int|string, string> $arguments */
function optionValue(array $arguments, string $option): ?string
{
    $prefix = $option . '=';

    foreach ($arguments as $argument) {
        if (str_starts_with($argument, $prefix)) {
            return substr($argument, strlen($prefix));
        }
    }

    return null;
}

function fail(string $message): never
{
    fwrite(STDERR, $message . PHP_EOL);

    exit(1);
}

function packageCountFromCatalogueTest(string $path): int
{
    if (! is_file($path)) {
        fail(sprintf('Package catalogue test could not be read: %s.', $path));
    }

    $contents = file_get_contents($path);

    if ($contents === false) {
        fail(sprintf('Package catalogue test could not be read: %s.', $path));
    }

    $marker = "it('loads the complete first party product catalogue'";
    $offset = strpos($contents, $marker);

    if ($offset === false) {
        fail('Package catalogue test does not contain the complete first party catalogue assertion.');
    }

    $catalogueTest = substr($contents, $offset, 5000);

    if (preg_match('/expect\(\$catalogue\)->toHaveCount\(\s*(\d+)\s*\)/', $catalogueTest, $matches) !== 1) {
        fail('Package catalogue test does not expose a complete catalogue count assertion.');
    }

    return (int) $matches[1];
}

function testCountFromListOutput(string $path): int
{
    if (! is_file($path)) {
        fail(sprintf('Pest test-list output could not be read: %s.', $path));
    }

    $contents = file_get_contents($path);

    if ($contents === false) {
        fail(sprintf('Pest test-list output could not be read: %s.', $path));
    }

    $count = preg_match_all('/^ - .+$/m', $contents);

    if (! is_int($count) || $count < 1) {
        fail('Pest test-list output does not contain any discovered tests.');
    }

    return $count;
}

function testCountFromPest(string $root): int
{
    $pest = $root . '/vendor/bin/pest';

    if (! is_file($pest)) {
        fail(sprintf('Pest is unavailable at %s; install dependencies before updating metrics.', $pest));
    }

    $command = sprintf(
        '%s %s --list-tests --configuration=phpunit.xml 2>&1',
        escapeshellarg(PHP_BINARY),
        escapeshellarg($pest),
    );
    $output = [];
    $exitCode = 0;
    exec($command, $output, $exitCode);

    if ($exitCode !== 0) {
        fail(sprintf("Pest test discovery failed with exit code %d:\n%s", $exitCode, implode(PHP_EOL, array_slice($output, -20))));
    }

    $count = preg_match_all('/^ - .+$/m', implode(PHP_EOL, $output));

    if (! is_int($count) || $count < 1) {
        fail('Pest test discovery returned no test IDs.');
    }

    return $count;
}

/** @param array<string, int|string> $metrics */
function writeJson(string $path, array $metrics): void
{
    $directory = dirname($path);

    if (! is_dir($directory) && ! mkdir($directory, 0775, true) && ! is_dir($directory)) {
        fail(sprintf('Unable to create metrics directory: %s.', $directory));
    }

    try {
        $contents = json_encode($metrics, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR) . PHP_EOL;
    } catch (JsonException $jsonException) {
        fail(sprintf('Unable to encode metrics: %s.', $jsonException->getMessage()));
    }

    if (file_put_contents($path, $contents) === false) {
        fail(sprintf('Unable to write metrics: %s.', $path));
    }
}
