<?php

declare(strict_types=1);

// Split publishing copies exact package trees, so shared repository policy must
// be materialised inside each package before its source commit is released.
$root = dirname(__DIR__);
if (array_diff(array_slice($argv, 1), ['--check']) !== []) {
    fwrite(STDERR, "Usage: php scripts/sync-split-repository-health.php [--check]\n");

    exit(2);
}

$check = in_array('--check', $argv, true);
/** @var list<array{path: string}> $packages */
$packages = json_decode(splitRepositoryHealthSource($root . '/config/release-packages.json'), true, 512, JSON_THROW_ON_ERROR);
$shared = $root . '/.github/split-repository';
$failures = [];

foreach ($packages as $package) {
    $path = $package['path'];
    $ecosystems = ['composer', 'github-actions'];

    if (is_file($root . '/' . $path . '/package.json')) {
        $ecosystems[] = 'npm';
    }

    $dependabot = "# Generated by scripts/sync-split-repository-health.php.\nversion: 2\nupdates:\n";

    foreach ($ecosystems as $ecosystem) {
        $dependabot .= "  - package-ecosystem: '{$ecosystem}'\n    directory: '/'\n    schedule:\n      interval: 'weekly'\n    cooldown:\n      default-days: 3\n";
    }

    $files = [
        'SECURITY.md' => splitRepositoryHealthSource($root . '/SECURITY.md'),
        '.github/dependabot.yml' => $dependabot,
        '.github/workflows/forward-pr-to-monorepo.yml' => splitRepositoryHealthSource($shared . '/forward-pr-to-monorepo.yml'),
        '.gitattributes' => splitRepositoryHealthSource($shared . '/.gitattributes'),
    ];

    foreach ($files as $relative => $contents) {
        $destination = $root . '/' . $path . '/' . $relative;

        if (is_file($destination) && file_get_contents($destination) === $contents) {
            continue;
        }

        if ($check) {
            $failures[] = $path . '/' . $relative;

            continue;
        }

        if (! is_dir(dirname($destination)) && ! mkdir(dirname($destination), 0755, true)) {
            throw new RuntimeException('Cannot create directory for ' . $destination);
        }

        if (file_put_contents($destination, $contents) === false) {
            throw new RuntimeException('Cannot write ' . $destination);
        }

        fwrite(STDOUT, 'Updated ' . $path . '/' . $relative . PHP_EOL);
    }
}

if ($failures !== []) {
    fwrite(STDERR, "Split repository health files are missing or stale:\n" . implode("\n", $failures) . "\nRun php scripts/sync-split-repository-health.php.\n");

    exit(1);
}

fwrite(STDOUT, "Split repository health files are aligned.\n");

function splitRepositoryHealthSource(string $path): string
{
    $contents = file_get_contents($path);

    if ($contents === false) {
        throw new RuntimeException('Cannot read split repository health source ' . $path);
    }

    return $contents;
}
